- name: Ejecutar procesamiento y envío de correo
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          URL_IMAGEN: ${{ secrets.URL_IMAGEN }}
        run: python procesar_ranking.py
