name: Procesar Reembolsos Google Drive

on:
  schedule:
    - cron: '*/10 * * * *' # Se ejecuta automáticamente cada 10 minutos
  workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaña Actions en GitHub

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install google-generativeai pandas openpyxl google-api-python-client google-auth

      - name: Ejecutar script de procesamiento
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          GOOGLE_DRIVE_FOLDER_ID: "1gGpIQGveFGIEzVWfwRqpmg89nOtcue6H"
        run: |
          python main.py
