name: Procesar Reembolsos Google Drive

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install google-generativeai pandas openpyxl google-api-python-client google-auth

      - name: Ejecutar script de procesamiento
        env:
          GEMINI_API_REEMBOLSO: ${{ secrets.GEMINI_API_REEMBOLSO }}
          GEMINI_API_KEY_2: ${{ secrets.GEMINI_API_KEY_2 }}
          GEMINI_API_KEY_3: ${{ secrets.GEMINI_API_KEY_3 }}
          GEMINI_API_KEY_4: ${{ secrets.GEMINI_API_KEY_4 }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          GOOGLE_DRIVE_FOLDER_ID: "1gGpIQGveFGIEzVWfwRqpmg89nOtcue6H"
        run: |
          python main.py
